<?php

use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\AgreementContentController;
use App\Http\Controllers\Admin\AgreementListContentController;
use App\Http\Controllers\Admin\AwardsOpportunityContentController;
use App\Http\Controllers\Admin\CertificateContentController;
use App\Http\Controllers\Admin\CampusLifeContentController;
use App\Http\Controllers\Admin\ContactContentController;
use App\Http\Controllers\Admin\MembershipContentController;
use App\Http\Controllers\Admin\MobilityPasantiasContentController;
use App\Http\Controllers\Admin\NewsContentController;
use App\Http\Controllers\Admin\NormativeContentController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\PresentationContentController;
use App\Http\Controllers\Admin\ProjectContentController;
use App\Http\Controllers\Admin\ProjectFundingContentController;
use App\Http\Controllers\Admin\ReportContentController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\ScholarshipBecasContentController;
use App\Http\Controllers\Admin\ScholarshipHubContentController;
use App\Http\Controllers\Admin\UserController;
use Illuminate\Support\Facades\Route;

Route::get('/', DashboardController::class)->name('dashboard');
Route::get('pages/{page}/presentation-content', [PresentationContentController::class, 'edit'])->name('pages.presentation.edit');
Route::put('pages/{page}/presentation-content', [PresentationContentController::class, 'update'])->name('pages.presentation.update');
Route::get('pages/{page}/agreement-content', [AgreementContentController::class, 'edit'])->name('pages.agreements.edit');
Route::put('pages/{page}/agreement-content', [AgreementContentController::class, 'update'])->name('pages.agreements.update');
Route::get('agreement-lists/{list}', [AgreementListContentController::class, 'edit'])->name('agreement-lists.edit');
Route::put('agreement-lists/{list}', [AgreementListContentController::class, 'update'])->name('agreement-lists.update');
Route::get('pages/{page}/project-content', [ProjectContentController::class, 'edit'])->name('pages.projects.edit');
Route::put('pages/{page}/project-content', [ProjectContentController::class, 'update'])->name('pages.projects.update');
Route::get('project-funding-content', [ProjectFundingContentController::class, 'edit'])->name('project-funding.edit');
Route::put('project-funding-content', [ProjectFundingContentController::class, 'update'])->name('project-funding.update');
Route::get('pages/{page}/membership-content', [MembershipContentController::class, 'edit'])->name('pages.memberships.edit');
Route::put('pages/{page}/membership-content', [MembershipContentController::class, 'update'])->name('pages.memberships.update');
Route::get('pages/{page}/news-content', [NewsContentController::class, 'edit'])->name('pages.news.edit');
Route::put('pages/{page}/news-content', [NewsContentController::class, 'update'])->name('pages.news.update');
Route::get('news/{news}/detail', [NewsContentController::class, 'editDetail'])->name('news.detail.edit');
Route::put('news/{news}/detail', [NewsContentController::class, 'updateDetail'])->name('news.detail.update');
Route::get('pages/{page}/normative-content', [NormativeContentController::class, 'edit'])->name('pages.normatives.edit');
Route::put('pages/{page}/normative-content', [NormativeContentController::class, 'update'])->name('pages.normatives.update');
Route::get('pages/{page}/report-content', [ReportContentController::class, 'edit'])->name('pages.reports.edit');
Route::put('pages/{page}/report-content', [ReportContentController::class, 'update'])->name('pages.reports.update');
Route::get('pages/{page}/certificate-content', [CertificateContentController::class, 'edit'])->name('pages.certificates.edit');
Route::put('pages/{page}/certificate-content', [CertificateContentController::class, 'update'])->name('pages.certificates.update');
Route::get('certificates/generate-code', [CertificateContentController::class, 'generateCode'])->name('certificates.generate-code');
Route::get('pages/{page}/contact-content', [ContactContentController::class, 'edit'])->name('pages.contact.edit');
Route::put('pages/{page}/contact-content', [ContactContentController::class, 'update'])->name('pages.contact.update');
Route::get('pages/{page}/campus-life-content', [CampusLifeContentController::class, 'edit'])->name('pages.campus-life.edit');
Route::put('pages/{page}/campus-life-content', [CampusLifeContentController::class, 'update'])->name('pages.campus-life.update');
Route::get('pages/{page}/scholarship-hub-content', [ScholarshipHubContentController::class, 'edit'])->name('pages.scholarship-hub.edit');
Route::put('pages/{page}/scholarship-hub-content', [ScholarshipHubContentController::class, 'update'])->name('pages.scholarship-hub.update');
Route::get('pages/{page}/scholarship-becas-content', [ScholarshipBecasContentController::class, 'edit'])->name('pages.scholarship-becas.edit');
Route::put('pages/{page}/scholarship-becas-content', [ScholarshipBecasContentController::class, 'update'])->name('pages.scholarship-becas.update');
Route::get('scholarship-items/{block}/detail', [ScholarshipBecasContentController::class, 'editDetail'])->name('scholarship-items.detail.edit');
Route::put('scholarship-items/{block}/detail', [ScholarshipBecasContentController::class, 'updateDetail'])->name('scholarship-items.detail.update');
Route::get('pages/{page}/mobility-pasantias-content', [MobilityPasantiasContentController::class, 'edit'])->name('pages.mobility-pasantias.edit');
Route::put('pages/{page}/mobility-pasantias-content', [MobilityPasantiasContentController::class, 'update'])->name('pages.mobility-pasantias.update');
Route::get('mobility-programs/{block}/detail', [MobilityPasantiasContentController::class, 'editDetail'])->name('mobility-programs.detail.edit');
Route::put('mobility-programs/{block}/detail', [MobilityPasantiasContentController::class, 'updateDetail'])->name('mobility-programs.detail.update');
Route::get('pages/{page}/awards-opportunities-content', [AwardsOpportunityContentController::class, 'edit'])->name('pages.awards-opportunities.edit');
Route::put('pages/{page}/awards-opportunities-content', [AwardsOpportunityContentController::class, 'update'])->name('pages.awards-opportunities.update');
Route::resource('pages', PageController::class)->except(['show', 'destroy']);
Route::resource('roles', RoleController::class)->except(['show']);
Route::resource('permissions', PermissionController::class)->only(['index', 'create', 'store', 'destroy']);
Route::resource('users', UserController::class)->except(['show']);
